version: '3.9'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    env_file:
      - .env
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./db/initdbs:/docker-entrypoint-initdb.d
      - ~/apps/mysql:/var/lib/mysql
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password
  appwebserver:
    build:
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      context: .
      network: host
    ports:
      - 8000:8000
    links:
      - "mysql:mysqlserverhost"
      - "elasticsearch:elasticsearchhost"
    env_file:
      - .env
    command: rails server -b 0.0.0.0 -p 8000 -e $RAILS_ENV